version: '3.8'
services:
  app:
    build: .
    container_name: nextjs-app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${POSTGRES_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
